CREATE DATABASE DBTREN;
USE DBTREN;

CREATE TABLE PASAJERO (
  id_pasajero INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(50) NOT NULL,
  apellidos VARCHAR(50) NOT NULL,
  genero CHAR(1) NOT NULL,
  tipo_documento CHAR(50) NOT NULL,
  numero_documento CHAR(50) NOT NULL,
  telefono VARCHAR(20) DEFAULT NULL,
  nacionalidad VARCHAR(50) NOT NULL,
  fech_nac DATE NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  contacto_compra BOOL DEFAULT NULL
);

CREATE TABLE PASAJERO_CORRIENTE (
  id_pasajero INT PRIMARY KEY,
  FOREIGN KEY (id_pasajero) REFERENCES PASAJERO(id_pasajero)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PASAJERO_EMPRESA (
  id_pasajero INT PRIMARY KEY,
  RUC VARCHAR(20) NOT NULL,
  direccion VARCHAR(100) NOT NULL,
  razonSocial VARCHAR(100) NOT NULL,
  FOREIGN KEY (id_pasajero) REFERENCES PASAJERO(id_pasajero)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EMPLEADO (
  id_empleado INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  documento VARCHAR(30) NOT NULL,
  fech_nac DATE NOT NULL,
  correo VARCHAR(100) DEFAULT NULL,
  edad INT DEFAULT NULL
);

CREATE TABLE ASESOR (
  id_empleado INT PRIMARY KEY,
  estacionTrabajo VARCHAR(50) NOT NULL,
  FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CHOFER (
  id_empleado INT PRIMARY KEY,
  licencia VARCHAR(30) NOT NULL,
  FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TRIPULANTE_DE_CABINA (
  id_empleado INT PRIMARY KEY,
  FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RUTA (
  id_ruta INT AUTO_INCREMENT PRIMARY KEY,
  ciudad_origen VARCHAR(50) NOT NULL,
  ciudad_destino VARCHAR(50) NOT NULL,
  estacion_origen VARCHAR(50) NOT NULL,
  estacion_destino VARCHAR(50) NOT NULL
);

CREATE TABLE CLASE (
  id_clase INT AUTO_INCREMENT PRIMARY KEY,
  clase VARCHAR(50) UNIQUE NOT NULL,
  precio_clase DECIMAL(10,2) NOT NULL,
  servicios VARCHAR(100) DEFAULT NULL
);

CREATE TABLE TRANSPORTE (
  id_tran INT AUTO_INCREMENT PRIMARY KEY,
  id_clase INT NOT NULL,
  aforo INT NOT NULL,
  FOREIGN KEY (id_clase) REFERENCES CLASE(id_clase)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HORARIO (
  id_horario INT AUTO_INCREMENT PRIMARY KEY,
  tipo VARCHAR(30) NOT NULL,
  hora_salida TIME NOT NULL,
  hora_llegada TIME NOT NULL,
  duracion_viaje TIME NOT NULL,
  id_ruta INT NOT NULL,
  FOREIGN KEY (id_ruta) REFERENCES RUTA(id_ruta)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PAGO (
  id_pago INT AUTO_INCREMENT PRIMARY KEY,
  metodo_pago VARCHAR(50) NOT NULL,
  fecha_pago DATE NOT NULL,
  monto DECIMAL(10,2) NOT NULL
);

CREATE TABLE RESERVA (
  id_reserva INT AUTO_INCREMENT PRIMARY KEY,
  tipo_viaje VARCHAR(50) NOT NULL,
  tipo_transporte VARCHAR(50) NOT NULL,
  fecha_reserva DATE NOT NULL,
  fecha_salida DATE DEFAULT NULL,
  fecha_retorno DATE DEFAULT NULL,
  id_pasajero INT NOT NULL,
  id_horario INT NOT NULL,
  id_pago INT UNIQUE NOT NULL,
  FOREIGN KEY (id_pasajero) REFERENCES PASAJERO(id_pasajero)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_horario) REFERENCES HORARIO(id_horario)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_pago) REFERENCES PAGO(id_pago)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RESERVA_FISICA (
  id_reserva INT PRIMARY KEY,
  id_asesor INT NOT NULL,
  FOREIGN KEY (id_reserva) REFERENCES RESERVA(id_reserva)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_asesor) REFERENCES ASESOR(id_empleado)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RESERVA_VIRTUAL(
  id_reserva INT PRIMARY KEY,
  FOREIGN KEY (id_reserva) REFERENCES RESERVA(id_reserva)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PASAJEROS_SECUNDARIOS (
  id_pasajerosec INT AUTO_INCREMENT PRIMARY KEY,
  id_reserva INT NOT NULL,
  FOREIGN KEY (id_reserva) REFERENCES RESERVA(id_reserva)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PS_ADULTO (
  id_pasajerosec INT PRIMARY KEY,
  nombres VARCHAR(50) NOT NULL,
  apellidos VARCHAR(50) NOT NULL,
  genero CHAR(1) NOT NULL,
  tipo_documento CHAR(50) NOT NULL,
  numero_documento CHAR(50) NOT NULL,
  nacionalidad VARCHAR(50) NOT NULL,
  fech_nac DATE NOT NULL,
  contacto_compra BOOL DEFAULT NULL,
  FOREIGN KEY (id_pasajerosec) REFERENCES PASAJEROS_SECUNDARIOS(id_pasajerosec)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PS_NIÑO (
  id_pasajerosec INT PRIMARY KEY,
  nombres VARCHAR(50) NOT NULL,
  apellidos VARCHAR(50) NOT NULL,
  genero CHAR(1) NOT NULL,
  tipo_documento CHAR(50) NOT NULL,
  numero_documento CHAR(50) NOT NULL,
  nacionalidad VARCHAR(50) NOT NULL,
  fech_nac DATE NOT NULL,
  FOREIGN KEY (id_pasajerosec) REFERENCES PASAJEROS_SECUNDARIOS(id_pasajerosec)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PS_INFANTE (
  id_pasajerosec INT PRIMARY KEY,
  resposable CHAR(50) NOT NULL,
  FOREIGN KEY (id_pasajerosec) REFERENCES PASAJEROS_SECUNDARIOS(id_pasajerosec)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ATIENDE (
  id_empleado INT,
  id_tran INT,
  PRIMARY KEY (id_empleado, id_tran),
  FOREIGN KEY (id_empleado) REFERENCES TRIPULANTE_DE_CABINA(id_empleado)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_tran) REFERENCES TRANSPORTE(id_tran)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDUCE (
  id_empleado INT,
  id_tran INT,
  PRIMARY KEY (id_empleado, id_tran),
  FOREIGN KEY (id_empleado) REFERENCES CHOFER(id_empleado)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_tran) REFERENCES TRANSPORTE(id_tran)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TIENE (
  id_tran INT,
  id_horario INT,
  PRIMARY KEY (id_horario, id_tran),
  FOREIGN KEY (id_horario) REFERENCES HORARIO(id_horario)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_tran) REFERENCES TRANSPORTE(id_tran)
    ON DELETE CASCADE ON UPDATE CASCADE
);
